# Imports

In [1]:
pip install category_encoders

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
pip show category_encoders

Name: category_encoders
Version: 2.7.0
Summary: A package for encoding categorical variables for machine learning
Home-page: 
Author: PaulWestenthanner
Author-email: paul@westenthanner.dev
License: BSD-3
Location: c:\Users\dilaw\fraud_project\venv\Lib\site-packages
Requires: numpy, pandas, patsy, scikit-learn, scipy, statsmodels
Required-by: 
Note: you may need to restart the kernel to use updated packages.


In [3]:
pip install --upgrade scikit-learn category_encoders

  Using cached scikit_learn-1.8.0-cp312-cp312-win_amd64.whl.metadata (11 kB)
  Using cached category_encoders-2.9.0-py3-none-any.whl.metadata (7.9 kB)
Using cached scikit_learn-1.8.0-cp312-cp312-win_amd64.whl (8.0 MB)
Using cached category_encoders-2.9.0-py3-none-any.whl (85 kB)
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.4.2
    Uninstalling scikit-learn-1.4.2:
      Successfully uninstalled scikit-learn-1.4.2
  Attempting uninstall: category_encoders
    Found existing installation: category_encoders 2.7.0
    Uninstalling category_encoders-2.7.0:
      Successfully uninstalled category_encoders-2.7.0
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
pip install scikit-learn==1.4.2 category_encoders==2.6.3

  Using cached scikit_learn-1.4.2-cp312-cp312-win_amd64.whl.metadata (11 kB)
  Using cached category_encoders-2.6.3-py2.py3-none-any.whl.metadata (8.0 kB)
Using cached scikit_learn-1.4.2-cp312-cp312-win_amd64.whl (10.6 MB)
Using cached category_encoders-2.6.3-py2.py3-none-any.whl (81 kB)
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.8.0
    Uninstalling scikit-learn-1.8.0:
      Successfully uninstalled scikit-learn-1.8.0
  Attempting uninstall: category_encoders
    Found existing installation: category_encoders 2.9.0
    Uninstalling category_encoders-2.9.0:
      Successfully uninstalled category_encoders-2.9.0
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
pip uninstall scikit-learn numpy scipy -y

Found existing installation: scikit-learn 1.4.2
Uninstalling scikit-learn-1.4.2:
  Successfully uninstalled scikit-learn-1.4.2
Found existing installation: numpy 1.26.4
Uninstalling numpy-1.26.4:
  Successfully uninstalled numpy-1.26.4
Found existing installation: scipy 1.17.1
Uninstalling scipy-1.17.1:
  Successfully uninstalled scipy-1.17.1
Note: you may need to restart the kernel to use updated packages.


In [6]:
pip install -r requirements.txt

  Using cached numpy-1.26.4-cp312-cp312-win_amd64.whl.metadata (61 kB)
  Using cached scikit_learn-1.4.2-cp312-cp312-win_amd64.whl.metadata (11 kB)
  Using cached scipy-1.17.1-cp312-cp312-win_amd64.whl.metadata (60 kB)
Using cached numpy-1.26.4-cp312-cp312-win_amd64.whl (15.5 MB)
Using cached scikit_learn-1.4.2-cp312-cp312-win_amd64.whl (10.6 MB)
Using cached scipy-1.17.1-cp312-cp312-win_amd64.whl (36.5 MB)
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [7]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.metrics import classification_report, roc_auc_score, confusion_matrix

from imblearn.over_sampling import SMOTE
from xgboost import XGBClassifier
import category_encoders as ce

In [8]:
df = pd.read_csv("../data/train_transaction.csv")

print(df.shape)
df.head()

(590540, 394)


,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,...,V330,V331,V332,V333,V334,V335,V336,V337,V338,V339
0,2987000,0,86400,68.5,W,13926,NaN,150.0,discover,142.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2987001,0,86401,29.0,W,2755,404.0,150.0,mastercard,102.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2987002,0,86469,59.0,W,4663,490.0,150.0,visa,166.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2987003,0,86499,50.0,W,18132,567.0,150.0,mastercard,117.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2987004,0,86506,50.0,H,4497,514.0,150.0,mastercard,102.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


In [9]:
target = "isFraud"

# Missing values handling

In [10]:
num_cols = df.select_dtypes(include=['int64', 'float64']).columns
cat_cols = df.select_dtypes(include=['object']).columns

num_cols = [col for col in num_cols if col != target]

# numerical
num_imputer = SimpleImputer(strategy='median')
df[num_cols] = num_imputer.fit_transform(df[num_cols])

# categorical
df[cat_cols] = df[cat_cols].fillna("missing")

print("Missing values handled")

C:\Users\dilaw\AppData\Local\Temp\ipykernel_24856\3546362792.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = df.select_dtypes(include=['object']).columns


Missing values handled


# High cardinality handling

In [11]:
high_card_cols = ['card1', 'card2', 'addr1']

for col in high_card_cols:
    if col in df.columns:
        freq = df[col].value_counts()
        df[col + "_freq"] = df[col].map(freq)

print("High-cardinality handled")

High-cardinality handled


C:\Users\dilaw\AppData\Local\Temp\ipykernel_24856\886353952.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col + "_freq"] = df[col].map(freq)


# Target encoding

In [12]:
encoder = ce.TargetEncoder(cols=cat_cols)
df[cat_cols] = encoder.fit_transform(df[cat_cols], df[target])

print("Encoding done")

Encoding done


# Train-Test Split

In [13]:
X = df.drop(columns=[target])
y = df[target]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("Split done")

Split done


# SMOTE

In [14]:
smote = SMOTE(random_state=42)

X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)

print("SMOTE applied")

SMOTE applied


In [15]:
model_smote = XGBClassifier(
    eval_metric='logloss',
    use_label_encoder=False
)

model_smote.fit(X_train_smote, y_train_smote)

c:\Users\dilaw\fraud_project\venv\Lib\site-packages\xgboost\training.py:200: UserWarning: [05:21:12] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, ...)

In [16]:
ratio = (y_train == 0).sum() / (y_train == 1).sum()

model_weight = XGBClassifier(
    scale_pos_weight=ratio,
    eval_metric='logloss',
    use_label_encoder=False
)

model_weight.fit(X_train, y_train)

c:\Users\dilaw\fraud_project\venv\Lib\site-packages\xgboost\training.py:200: UserWarning: [05:23:13] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, ...)

# Evaluation

In [17]:
# SMOTE
y_pred_smote = model_smote.predict(X_test)
y_prob_smote = model_smote.predict_proba(X_test)[:,1]

# Weighted
y_pred_weight = model_weight.predict(X_test)
y_prob_weight = model_weight.predict_proba(X_test)[:,1]

# Results

In [18]:
print("SMOTE Results")
print(classification_report(y_test, y_pred_smote))
print("AUC:", roc_auc_score(y_test, y_prob_smote))
print(confusion_matrix(y_test, y_pred_smote))

print("\nWeighted Results")
print(classification_report(y_test, y_pred_weight))
print("AUC:", roc_auc_score(y_test, y_prob_weight))
print(confusion_matrix(y_test, y_pred_weight))

SMOTE Results
              precision    recall  f1-score   support

           0       0.98      1.00      0.99    113975
           1       0.87      0.47      0.61      4133

    accuracy                           0.98    118108
   macro avg       0.93      0.74      0.80    118108
weighted avg       0.98      0.98      0.98    118108

AUC: 0.9296197952410068
[[113686    289]
 [  2174   1959]]

Weighted Results
              precision    recall  f1-score   support

           0       0.99      0.92      0.96    113975
           1       0.27      0.83      0.41      4133

    accuracy                           0.92    118108
   macro avg       0.63      0.87      0.68    118108
weighted avg       0.97      0.92      0.94    118108

AUC: 0.9480580460597611
[[104929   9046]
 [   714   3419]]


# Comparison Table

In [19]:
results = pd.DataFrame({
    "Method": ["SMOTE", "Class Weight"],
    "Recall": [
        classification_report(y_test, y_pred_smote, output_dict=True)['1']['recall'],
        classification_report(y_test, y_pred_weight, output_dict=True)['1']['recall']
    ],
    "F1": [
        classification_report(y_test, y_pred_smote, output_dict=True)['1']['f1-score'],
        classification_report(y_test, y_pred_weight, output_dict=True)['1']['f1-score']
    ],
    "AUC": [
        roc_auc_score(y_test, y_prob_smote),
        roc_auc_score(y_test, y_prob_weight)
    ]
})

results

,Method,Recall,F1,AUC
0,SMOTE,0.473990,0.614010,0.929620
1,Class Weight,0.827244,0.411977,0.948058


# Task 03

In [20]:
pip install lightgbm

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [21]:
from lightgbm import LGBMClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

In [22]:
lgb_model = LGBMClassifier()

lgb_model.fit(X_train, y_train)

y_pred_lgb = lgb_model.predict(X_test)
y_prob_lgb = lgb_model.predict_proba(X_test)[:,1]

[LightGBM] [Info] Number of positive: 16530, number of negative: 455902
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.630929 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 37371
[LightGBM] [Info] Number of data points in the train set: 472432, number of used features: 394
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.034989 -> initscore=-3.317101
[LightGBM] [Info] Start training from score -3.317101


In [23]:
rf = RandomForestClassifier(n_estimators=100)
rf.fit(X_train, y_train)

selector = SelectFromModel(rf, threshold='median')
X_train_fs = selector.transform(X_train)
X_test_fs = selector.transform(X_test)

c:\Users\dilaw\fraud_project\venv\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but SelectFromModel was fitted without feature names
  warnings.warn(
c:\Users\dilaw\fraud_project\venv\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but SelectFromModel was fitted without feature names
  warnings.warn(


In [24]:
rf_model = RandomForestClassifier(n_estimators=100)
rf_model.fit(X_train_fs, y_train)

y_pred_rf = rf_model.predict(X_test_fs)
y_prob_rf = rf_model.predict_proba(X_test_fs)[:,1]

In [25]:
def evaluate_model(name, y_true, y_pred, y_prob):
    print(f"\n{name}")
    print(classification_report(y_true, y_pred))
    print("AUC:", roc_auc_score(y_true, y_prob))
    print("Confusion Matrix:\n", confusion_matrix(y_true, y_pred))

In [26]:
evaluate_model("XGBoost SMOTE", y_test, y_pred_smote, y_prob_smote)
evaluate_model("XGBoost Weighted", y_test, y_pred_weight, y_prob_weight)
evaluate_model("LightGBM", y_test, y_pred_lgb, y_prob_lgb)
evaluate_model("Hybrid RF", y_test, y_pred_rf, y_prob_rf)


XGBoost SMOTE
              precision    recall  f1-score   support

           0       0.98      1.00      0.99    113975
           1       0.87      0.47      0.61      4133

    accuracy                           0.98    118108
   macro avg       0.93      0.74      0.80    118108
weighted avg       0.98      0.98      0.98    118108

AUC: 0.9296197952410068
Confusion Matrix:
 [[113686    289]
 [  2174   1959]]

XGBoost Weighted
              precision    recall  f1-score   support

           0       0.99      0.92      0.96    113975
           1       0.27      0.83      0.41      4133

    accuracy                           0.92    118108
   macro avg       0.63      0.87      0.68    118108
weighted avg       0.97      0.92      0.94    118108

AUC: 0.9480580460597611
Confusion Matrix:
 [[104929   9046]
 [   714   3419]]

LightGBM
              precision    recall  f1-score   support

           0       0.98      1.00      0.99    113975
           1       0.88      0.43     

In [27]:
results_task3 = pd.DataFrame({
    "Model": ["XGB_SMOTE", "XGB_Weight", "LightGBM", "Hybrid_RF"],
    "Recall": [
        classification_report(y_test, y_pred_smote, output_dict=True)['1']['recall'],
        classification_report(y_test, y_pred_weight, output_dict=True)['1']['recall'],
        classification_report(y_test, y_pred_lgb, output_dict=True)['1']['recall'],
        classification_report(y_test, y_pred_rf, output_dict=True)['1']['recall']
    ],
    "F1": [
        classification_report(y_test, y_pred_smote, output_dict=True)['1']['f1-score'],
        classification_report(y_test, y_pred_weight, output_dict=True)['1']['f1-score'],
        classification_report(y_test, y_pred_lgb, output_dict=True)['1']['f1-score'],
        classification_report(y_test, y_pred_rf, output_dict=True)['1']['f1-score']
    ],
    "AUC": [
        roc_auc_score(y_test, y_prob_smote),
        roc_auc_score(y_test, y_prob_weight),
        roc_auc_score(y_test, y_prob_lgb),
        roc_auc_score(y_test, y_prob_rf)
    ]
})

results_task3

,Model,Recall,F1,AUC
0,XGB_SMOTE,0.473990,0.614010,0.929620
1,XGB_Weight,0.827244,0.411977,0.948058
2,LightGBM,0.432616,0.580802,0.932121
3,Hybrid_RF,0.471328,0.628996,0.935023


# Task 04

In [28]:
baseline_model = XGBClassifier(
    eval_metric='logloss',
    use_label_encoder=False
)

baseline_model.fit(X_train, y_train)

y_pred_base = baseline_model.predict(X_test)
y_prob_base = baseline_model.predict_proba(X_test)[:,1]

c:\Users\dilaw\fraud_project\venv\Lib\site-packages\xgboost\training.py:200: UserWarning: [05:59:44] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


In [29]:
ratio = (y_train == 0).sum() / (y_train == 1).sum()

cost_model = XGBClassifier(
    scale_pos_weight=ratio * 2,  # stronger penalty
    eval_metric='logloss',
    use_label_encoder=False
)

cost_model.fit(X_train, y_train)

y_pred_cost = cost_model.predict(X_test)
y_prob_cost = cost_model.predict_proba(X_test)[:,1]

c:\Users\dilaw\fraud_project\venv\Lib\site-packages\xgboost\training.py:200: UserWarning: [06:00:49] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


In [30]:
def evaluate(name, y_true, y_pred, y_prob):
    print(f"\n{name}")
    print(classification_report(y_true, y_pred))
    print("AUC:", roc_auc_score(y_true, y_prob))
    print("Confusion Matrix:\n", confusion_matrix(y_true, y_pred))

In [31]:
evaluate("Baseline Model", y_test, y_pred_base, y_prob_base)
evaluate("Cost-Sensitive Model", y_test, y_pred_cost, y_prob_cost)


Baseline Model
              precision    recall  f1-score   support

           0       0.98      1.00      0.99    113975
           1       0.90      0.50      0.64      4133

    accuracy                           0.98    118108
   macro avg       0.94      0.75      0.82    118108
weighted avg       0.98      0.98      0.98    118108

AUC: 0.944264159873502
Confusion Matrix:
 [[113733    242]
 [  2064   2069]]

Cost-Sensitive Model
              precision    recall  f1-score   support

           0       1.00      0.85      0.92    113975
           1       0.18      0.88      0.30      4133

    accuracy                           0.86    118108
   macro avg       0.59      0.87      0.61    118108
weighted avg       0.97      0.86      0.90    118108

AUC: 0.9463931918884627
Confusion Matrix:
 [[97329 16646]
 [  479  3654]]


In [32]:
import pandas as pd

results_task4 = pd.DataFrame({
    "Model": ["Baseline", "Cost-Sensitive"],
    "Recall": [
        classification_report(y_test, y_pred_base, output_dict=True)['1']['recall'],
        classification_report(y_test, y_pred_cost, output_dict=True)['1']['recall']
    ],
    "F1": [
        classification_report(y_test, y_pred_base, output_dict=True)['1']['f1-score'],
        classification_report(y_test, y_pred_cost, output_dict=True)['1']['f1-score']
    ],
    "AUC": [
        roc_auc_score(y_test, y_prob_base),
        roc_auc_score(y_test, y_prob_cost)
    ]
})

results_task4



,Model,Recall,F1,AUC
0,Baseline,0.500605,0.642148,0.944264
1,Cost-Sensitive,0.884104,0.299104,0.946393
